export const data = [
  {
    img: "https://live.themewild.com/moplay/assets/img/movie/01.jpg",
    ratingnum: 5.3,
    title: "Ghost Rider",
    duration: "2h 30min",
    movietype: "Action, Fantasy",
  },
  {
    img: "https://live.themewild.com/moplay/assets/img/movie/02.jpg",
    ratingnum: 7.9,
    title: "Iron Man",
    duration: "2h 10min",
    movietype: "Action, Fantasy",
  },
  {
    img: "https://live.themewild.com/moplay/assets/img/movie/03.jpg",
    ratingnum: 6.5,
    title: "Oblivion",
    duration: "2h 10min",
    movietype: "Action, Fantasy",
  },
  {
    img: "https://live.themewild.com/moplay/assets/img/movie/08.jpg",
    ratingnum: 5.8,
    title: "Gran Turismo",
    duration: "2h 10min",
    movietype: "Action, Sports",
  },
  {
    img: "https://live.themewild.com/moplay/assets/img/movie/14.jpg",
    ratingnum: 8.2,
    title: "Angry Birds",
    duration: "2h 10min",
    movietype: "Animation",
  },
  {
    img: "https://live.themewild.com/moplay/assets/img/movie/18.jpg",
    ratingnum: 9,
    title: "John Wick",
    duration: "2h 10min",
    movietype: "Action, Crime",
  },
  {
    img: "https://live.themewild.com/moplay/assets/img/movie/20.jpg",
    ratingnum: 7.1,
    title: "Sherlock Holmes",
    duration: "2h 10min",
    movietype: "Action, Drama",
  },
  {
    img: "https://live.themewild.com/moplay/assets/img/movie/06.jpg",
    ratingnum: 10,
    title: "The Avatar",
    duration: "2h 10min",
    movietype: "Action, Fantasy",
  },
  {
    img: "https://live.themewild.com/moplay/assets/img/movie/07.jpg",
    ratingnum: 9.4,
    title: "Mission Impossible",
    duration: "2h 10min",
    movietype: "Action, Fantasy",
  },
  {
    img: "https://live.themewild.com/moplay/assets/img/movie/04.jpg",
    ratingnum: 6.6,
    title: "Tron",
    duration: "2h 10min",
    movietype: "Action, Fantasy",
  },
  {
    img: "https://live.themewild.com/moplay/assets/img/movie/05.jpg",
    ratingnum: 6.6,
    title: "The Flash",
    duration: "2h 10min",
    movietype: "Action, Fantasy",
  },
  {
    img: "https://live.themewild.com/moplay/assets/img/movie/10.jpg",
    ratingnum: 5,
    title: "Blue Beetle",
    duration: "2h 10min",
    movietype: "Action, Fantasy",
  },
  {
    img: "https://live.themewild.com/moplay/assets/img/movie/15.jpg",
    ratingnum: 8,
    title: "Frozen",
    duration: "2h 10min",
    movietype: "Animation",
  },
  {
    img: "https://live.themewild.com/moplay/assets/img/movie/19.jpg",
    ratingnum: 7.1,
    title: "Jumanji",
    duration: "2h 10min",
    movietype: "Action, Fantasy",
  },
  {
    img: "https://live.themewild.com/moplay/assets/img/movie/09.jpg",
    ratingnum: 5.7,
    title: "Meg 2: The Trench",
    duration: "2h 10min",
    movietype: "Action, Fantasy",
  },
];
